// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function mmToPixels(mm) {
  return mm * 3.7795275591 | 0;
}

function getPaperSize(size) {
  switch (size) {
    case "A3" :
        return {
                width: 1123,
                height: 1587,
                widthMm: 297.0,
                heightMm: 420.0
              };
    case "A5" :
        return {
                width: 559,
                height: 794,
                widthMm: 148.0,
                heightMm: 210.0
              };
    case "Legal" :
        return {
                width: 816,
                height: 1344,
                widthMm: 215.9,
                heightMm: 355.6
              };
    case "Letter" :
        return {
                width: 816,
                height: 1056,
                widthMm: 215.9,
                heightMm: 279.4
              };
    case "Square" :
        return {
                width: 1134,
                height: 1134,
                widthMm: 300.0,
                heightMm: 300.0
              };
    case "Tabloid" :
        return {
                width: 1056,
                height: 1632,
                widthMm: 279.4,
                heightMm: 431.8
              };
    default:
      return {
              width: 794,
              height: 1123,
              widthMm: 210.0,
              heightMm: 297.0
            };
  }
}

function customPaperSize(widthMm, heightMm) {
  return {
          width: widthMm * 3.7795275591 | 0,
          height: heightMm * 3.7795275591 | 0,
          widthMm: widthMm,
          heightMm: heightMm
        };
}

var currentPaperSize = {
  contents: getPaperSize("A4")
};

var currentMarginMm = {
  contents: 10.0
};

var currentPaddingMm = {
  contents: 5.0
};

function getCurrentPaperSize() {
  return currentPaperSize.contents;
}

function createPlotterSketch(drawFn) {
  return function () {
    return function (p) {
      var updateCanvasSize = function () {
        var selector = document.getElementById("paper-size");
        if (selector == null) {
          return ;
        }
        var size = selector.value;
        var customDiv = document.getElementById("custom-size");
        if (customDiv == null) {
          return ;
        }
        var divStyle = customDiv.style;
        if (size === "Custom") {
          divStyle.display = "flex";
        } else {
          divStyle.display = "none";
          currentPaperSize.contents = getPaperSize(size);
          p.resizeCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
          p.background(255);
        }
      };
      var applyCustomSize = function () {
        var widthInput = document.getElementById("custom-width");
        var heightInput = document.getElementById("custom-height");
        if (widthInput == null) {
          return ;
        }
        if (heightInput == null) {
          return ;
        }
        var widthMm = Core__Option.getOr(Core__Float.fromString(widthInput.value), 210.0);
        var heightMm = Core__Option.getOr(Core__Float.fromString(heightInput.value), 297.0);
        currentPaperSize.contents = customPaperSize(widthMm, heightMm);
        p.resizeCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
        p.background(255);
      };
      var createSpacingControls = function () {
        var controlsDiv = document.getElementById("paper-settings-controls");
        if (controlsDiv == null) {
          console.log("Paper settings controls container not found");
          return ;
        }
        controlsDiv.innerHTML = "";
        controlsDiv.className = "mb-6 space-y-4";
        var marginLabel = document.createElement("label");
        marginLabel.textContent = "Margin (mm) - Bleed/Cut Area";
        marginLabel.setAttribute("for", "margin-size");
        marginLabel.className = "block text-sm font-medium text-zinc-300 mb-1";
        controlsDiv.appendChild(marginLabel);
        var marginInput = document.createElement("input");
        marginInput.setAttribute("type", "number");
        marginInput.setAttribute("id", "margin-size");
        marginInput.value = "10";
        marginInput.setAttribute("min", "0");
        marginInput.setAttribute("max", "50");
        marginInput.setAttribute("step", "1");
        marginInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
        marginInput.addEventListener("input", (function () {
                var value = Core__Option.getOr(Core__Float.fromString(marginInput.value), 10.0);
                currentMarginMm.contents = value;
              }));
        controlsDiv.appendChild(marginInput);
        var paddingLabel = document.createElement("label");
        paddingLabel.textContent = "Padding (mm) - Extra Safe Space";
        paddingLabel.setAttribute("for", "padding-size");
        paddingLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
        controlsDiv.appendChild(paddingLabel);
        var paddingInput = document.createElement("input");
        paddingInput.setAttribute("type", "number");
        paddingInput.setAttribute("id", "padding-size");
        paddingInput.value = "5";
        paddingInput.setAttribute("min", "0");
        paddingInput.setAttribute("max", "50");
        paddingInput.setAttribute("step", "1");
        paddingInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
        paddingInput.addEventListener("input", (function () {
                var value = Core__Option.getOr(Core__Float.fromString(paddingInput.value), 5.0);
                currentPaddingMm.contents = value;
              }));
        controlsDiv.appendChild(paddingInput);
        console.log("Spacing controls created");
      };
      p.setup = (function () {
          p.createCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
          p.background(255);
          createSpacingControls();
          var selector = document.getElementById("paper-size");
          if (!(selector == null)) {
            selector.addEventListener("change", updateCanvasSize);
          }
          var applyBtn = document.getElementById("apply-custom");
          if (!(applyBtn == null)) {
            applyBtn.addEventListener("click", applyCustomSize);
            return ;
          }
          
        });
      p.draw = (function () {
          p.background(255);
          var marginPx = currentMarginMm.contents * 3.7795275591;
          var paddingPx = currentPaddingMm.contents * 3.7795275591;
          var totalSpacePx = marginPx + paddingPx;
          p.noFill();
          p.stroke(200);
          p.strokeWeight(1);
          p.rect(marginPx, marginPx, currentPaperSize.contents.width - marginPx * 2.0, currentPaperSize.contents.height - marginPx * 2.0);
          if (paddingPx > 0.0) {
            p.stroke(150);
            p.strokeWeight(1);
            p.rect(totalSpacePx, totalSpacePx, currentPaperSize.contents.width - totalSpacePx * 2.0, currentPaperSize.contents.height - totalSpacePx * 2.0);
          }
          var totalSpaceMm = currentMarginMm.contents + currentPaddingMm.contents;
          var drawableSize_width = currentPaperSize.contents.width - (totalSpacePx * 2.0 | 0) | 0;
          var drawableSize_height = currentPaperSize.contents.height - (totalSpacePx * 2.0 | 0) | 0;
          var drawableSize_widthMm = currentPaperSize.contents.widthMm - totalSpaceMm * 2.0;
          var drawableSize_heightMm = currentPaperSize.contents.heightMm - totalSpaceMm * 2.0;
          var drawableSize = {
            width: drawableSize_width,
            height: drawableSize_height,
            widthMm: drawableSize_widthMm,
            heightMm: drawableSize_heightMm
          };
          p.push();
          p.translate(totalSpacePx, totalSpacePx);
          drawFn(p, drawableSize);
          p.pop();
        });
    };
  };
}

export {
  mmToPixels ,
  getPaperSize ,
  customPaperSize ,
  currentPaperSize ,
  currentMarginMm ,
  currentPaddingMm ,
  getCurrentPaperSize ,
  createPlotterSketch ,
}
/* currentPaperSize Not a pure module */
