// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function mmToPixels(mm) {
  return mm * 3.7795275591 | 0;
}

function getPaperSize(size) {
  switch (size) {
    case "A3" :
        return {
                width: 1123,
                height: 1587,
                widthMm: 297.0,
                heightMm: 420.0
              };
    case "A5" :
        return {
                width: 559,
                height: 794,
                widthMm: 148.0,
                heightMm: 210.0
              };
    case "Legal" :
        return {
                width: 816,
                height: 1344,
                widthMm: 215.9,
                heightMm: 355.6
              };
    case "Letter" :
        return {
                width: 816,
                height: 1056,
                widthMm: 215.9,
                heightMm: 279.4
              };
    case "Square" :
        return {
                width: 1134,
                height: 1134,
                widthMm: 300.0,
                heightMm: 300.0
              };
    case "Tabloid" :
        return {
                width: 1056,
                height: 1632,
                widthMm: 279.4,
                heightMm: 431.8
              };
    default:
      return {
              width: 794,
              height: 1123,
              widthMm: 210.0,
              heightMm: 297.0
            };
  }
}

function customPaperSize(widthMm, heightMm) {
  return {
          width: widthMm * 3.7795275591 | 0,
          height: heightMm * 3.7795275591 | 0,
          widthMm: widthMm,
          heightMm: heightMm
        };
}

function createPlotterSketch(drawFn) {
  return function () {
    return function (p) {
      var currentSize = {
        contents: getPaperSize("A4")
      };
      var updateCanvasSize = function () {
        var selector = document.getElementById("paper-size");
        if (selector == null) {
          return ;
        }
        var size = selector.value;
        var customDiv = document.getElementById("custom-size");
        if (customDiv == null) {
          return ;
        }
        var divStyle = customDiv.style;
        if (size === "Custom") {
          divStyle.display = "flex";
        } else {
          divStyle.display = "none";
          currentSize.contents = getPaperSize(size);
          p.resizeCanvas(currentSize.contents.width, currentSize.contents.height);
          p.background(255);
        }
      };
      var applyCustomSize = function () {
        var widthInput = document.getElementById("custom-width");
        var heightInput = document.getElementById("custom-height");
        if (widthInput == null) {
          return ;
        }
        if (heightInput == null) {
          return ;
        }
        var widthMm = Core__Option.getOr(Core__Float.fromString(widthInput.value), 210.0);
        var heightMm = Core__Option.getOr(Core__Float.fromString(heightInput.value), 297.0);
        currentSize.contents = customPaperSize(widthMm, heightMm);
        p.resizeCanvas(currentSize.contents.width, currentSize.contents.height);
        p.background(255);
      };
      var getTimestampFilename = function (extension) {
        var date = (new Date());
        var timestamp = ((d) => d.toISOString())(date);
        return timestamp + "." + extension;
      };
      var exportPNG = function () {
        var canvas = p.canvas;
        var dataUrl = canvas.toDataURL("image/png", 1.0);
        var link = document.createElement("a");
        link.href = dataUrl;
        link.download = getTimestampFilename("png");
        var linkStyle = link.style;
        linkStyle.display = "none";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      };
      var exportSVG = function () {
        var svgWidth = currentSize.contents.widthMm;
        var svgHeight = currentSize.contents.heightMm;
        var svgHeader = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"" + svgWidth.toString() + "mm\" height=\"" + svgHeight.toString() + "mm\" viewBox=\"0 0 " + currentSize.contents.width.toString() + " " + currentSize.contents.height.toString() + "\">\n  <rect width=\"100%\" height=\"100%\" fill=\"white\"/>\n  <g stroke=\"black\" fill=\"none\">";
        var svgContent = svgHeader + "  </g>\n</svg>";
        var blob = ((content) => new Blob([content], {type: 'image/svg+xml'}))(svgContent);
        var url = ((b) => URL.createObjectURL(b))(blob);
        var link = document.createElement("a");
        link.href = url;
        link.download = getTimestampFilename("svg");
        var linkStyle = link.style;
        linkStyle.display = "none";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        return ((u) => URL.revokeObjectURL(u))(url);
      };
      var handleExport = function () {
        var formatSelect = document.getElementById("export-format");
        if (formatSelect == null) {
          return ;
        }
        var format = formatSelect.value;
        if (format === "png") {
          return exportPNG();
        } else if (format === "svg") {
          return exportSVG();
        } else {
          return ;
        }
      };
      p.setup = (function () {
          p.createCanvas(currentSize.contents.width, currentSize.contents.height);
          p.background(255);
          var selector = document.getElementById("paper-size");
          if (!(selector == null)) {
            selector.addEventListener("change", updateCanvasSize);
          }
          var applyBtn = document.getElementById("apply-custom");
          if (!(applyBtn == null)) {
            applyBtn.addEventListener("click", applyCustomSize);
          }
          var exportBtn = document.getElementById("export-btn");
          if (!(exportBtn == null)) {
            exportBtn.addEventListener("click", handleExport);
            return ;
          }
          
        });
      p.draw = (function () {
          p.background(255);
          p.noFill();
          p.stroke(0);
          p.strokeWeight(2);
          p.rect(10.0, 10.0, currentSize.contents.width - 20 | 0, currentSize.contents.height - 20 | 0);
          drawFn(p, currentSize.contents);
        });
    };
  };
}

export {
  mmToPixels ,
  getPaperSize ,
  customPaperSize ,
  createPlotterSketch ,
}
/* No side effect */
