// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PlotterFrame from "./PlotterFrame.res.mjs";

function draw(p, paperSize) {
  p.stroke(0, 0, 0);
  p.strokeWeight(1);
  p.noFill();
  var centerX = paperSize.width / 2.0;
  var centerY = paperSize.height / 2.0;
  var maxRadius = Math.min(centerX, centerY) - 50.0;
  for(var i = 1; i <= 20; ++i){
    var radius = maxRadius * i / 20;
    p.circle(centerX, centerY, radius * 2.0);
  }
  var currentMarginMm = PlotterFrame.currentMarginMm.contents;
  var currentPaddingMm = PlotterFrame.currentPaddingMm.contents;
  var totalSpacePx = (currentMarginMm + currentPaddingMm) * 3.7795275591;
  var adjustedMouseX = p.mouseX - totalSpacePx;
  var adjustedMouseY = p.mouseY - totalSpacePx;
  if (adjustedMouseX > 0.0 && adjustedMouseY > 0.0 && adjustedMouseX < paperSize.width && adjustedMouseY < paperSize.height) {
    p.stroke(100, 150, 255);
    p.strokeWeight(1);
    p.line(centerX, centerY, adjustedMouseX, adjustedMouseY);
    p.circle(adjustedMouseX, adjustedMouseY, 20.0);
    return ;
  }
  
}

var createSketch = PlotterFrame.createPlotterSketch(draw);

export {
  draw ,
  createSketch ,
}
/* createSketch Not a pure module */
