// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function mmToPixels(mm) {
  return mm * 3.7795275591 | 0;
}

function getPaperSize(size) {
  switch (size) {
    case "A3" :
        return {
                width: 1123,
                height: 1587,
                widthMm: 297.0,
                heightMm: 420.0
              };
    case "A5" :
        return {
                width: 559,
                height: 794,
                widthMm: 148.0,
                heightMm: 210.0
              };
    case "Legal" :
        return {
                width: 816,
                height: 1344,
                widthMm: 215.9,
                heightMm: 355.6
              };
    case "Letter" :
        return {
                width: 816,
                height: 1056,
                widthMm: 215.9,
                heightMm: 279.4
              };
    case "Square" :
        return {
                width: 1134,
                height: 1134,
                widthMm: 300.0,
                heightMm: 300.0
              };
    case "Tabloid" :
        return {
                width: 1056,
                height: 1632,
                widthMm: 279.4,
                heightMm: 431.8
              };
    default:
      return {
              width: 794,
              height: 1123,
              widthMm: 210.0,
              heightMm: 297.0
            };
  }
}

function customPaperSize(widthMm, heightMm) {
  return {
          width: widthMm * 3.7795275591 | 0,
          height: heightMm * 3.7795275591 | 0,
          widthMm: widthMm,
          heightMm: heightMm
        };
}

var currentPaperSize = {
  contents: getPaperSize("A4")
};

function getCurrentPaperSize() {
  return currentPaperSize.contents;
}

function createPlotterSketch(drawFn) {
  return function () {
    return function (p) {
      var updateCanvasSize = function () {
        var selector = document.getElementById("paper-size");
        if (selector == null) {
          return ;
        }
        var size = selector.value;
        var customDiv = document.getElementById("custom-size");
        if (customDiv == null) {
          return ;
        }
        var divStyle = customDiv.style;
        if (size === "Custom") {
          divStyle.display = "flex";
        } else {
          divStyle.display = "none";
          currentPaperSize.contents = getPaperSize(size);
          p.resizeCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
          p.background(255);
        }
      };
      var applyCustomSize = function () {
        var widthInput = document.getElementById("custom-width");
        var heightInput = document.getElementById("custom-height");
        if (widthInput == null) {
          return ;
        }
        if (heightInput == null) {
          return ;
        }
        var widthMm = Core__Option.getOr(Core__Float.fromString(widthInput.value), 210.0);
        var heightMm = Core__Option.getOr(Core__Float.fromString(heightInput.value), 297.0);
        currentPaperSize.contents = customPaperSize(widthMm, heightMm);
        p.resizeCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
        p.background(255);
      };
      p.setup = (function () {
          p.createCanvas(currentPaperSize.contents.width, currentPaperSize.contents.height);
          p.background(255);
          var selector = document.getElementById("paper-size");
          if (!(selector == null)) {
            selector.addEventListener("change", updateCanvasSize);
          }
          var applyBtn = document.getElementById("apply-custom");
          if (!(applyBtn == null)) {
            applyBtn.addEventListener("click", applyCustomSize);
            return ;
          }
          
        });
      p.draw = (function () {
          p.background(255);
          p.noFill();
          p.stroke(200);
          p.strokeWeight(1);
          p.rect(40.0, 40.0, currentPaperSize.contents.width - 40.0 * 2.0, currentPaperSize.contents.height - 40.0 * 2.0);
          var marginedSize_width = currentPaperSize.contents.width - (40.0 * 2.0 | 0) | 0;
          var marginedSize_height = currentPaperSize.contents.height - (40.0 * 2.0 | 0) | 0;
          var marginedSize_widthMm = currentPaperSize.contents.widthMm - 40.0 * 2.0 / 3.7795275591;
          var marginedSize_heightMm = currentPaperSize.contents.heightMm - 40.0 * 2.0 / 3.7795275591;
          var marginedSize = {
            width: marginedSize_width,
            height: marginedSize_height,
            widthMm: marginedSize_widthMm,
            heightMm: marginedSize_heightMm
          };
          p.push();
          p.translate(40.0, 40.0);
          drawFn(p, marginedSize);
          p.pop();
        });
    };
  };
}

export {
  mmToPixels ,
  getPaperSize ,
  customPaperSize ,
  currentPaperSize ,
  getCurrentPaperSize ,
  createPlotterSketch ,
}
/* currentPaperSize Not a pure module */
