// Generated by ReScript, PLEASE EDIT WITH CARE


function sketch(p) {
  p.setup = (function () {
      p.createCanvas(800, 600);
      p.background(220);
    });
  p.draw = (function () {
      p.background(240, 240, 245);
      p.fill(100, 150, 255);
      p.noStroke();
      p.circle(p.mouseX, p.mouseY, 50.0);
      p.fill(255, 100, 100);
      p.circle(400.0, 300.0, 100.0);
      var time = p.frameCount;
      var x = 400.0 + Math.cos(time * 0.05) * 200.0;
      var y = 300.0 + Math.sin(time * 0.05) * 200.0;
      p.fill(100, 255, 150);
      p.circle(x, y, 60.0);
    });
}

((new p5(sketch)));

export {
  sketch ,
}
/*  Not a pure module */
