// Generated by ReScript, PLEASE EDIT WITH CARE


function getPaperSize(size) {
  switch (size) {
    case "A3" :
        return {
                width: 1123,
                height: 1587
              };
    case "A5" :
        return {
                width: 559,
                height: 794
              };
    case "Legal" :
        return {
                width: 816,
                height: 1344
              };
    case "Letter" :
        return {
                width: 816,
                height: 1056
              };
    case "Square" :
        return {
                width: 1134,
                height: 1134
              };
    case "Tabloid" :
        return {
                width: 1056,
                height: 1632
              };
    default:
      return {
              width: 794,
              height: 1123
            };
  }
}

function sketch(p) {
  var currentSize = {
    contents: getPaperSize("A4")
  };
  var updateCanvasSize = function () {
    var selector = document.getElementById("paper-size");
    if (selector == null) {
      return ;
    }
    var size = selector.value;
    currentSize.contents = getPaperSize(size);
    p.resizeCanvas(currentSize.contents.width, currentSize.contents.height);
    p.background(255);
  };
  p.setup = (function () {
      p.createCanvas(currentSize.contents.width, currentSize.contents.height);
      p.background(255);
      var selector = document.getElementById("paper-size");
      if (!(selector == null)) {
        selector.addEventListener("change", updateCanvasSize);
        return ;
      }
      
    });
  p.draw = (function () {
      p.background(255);
      p.noFill();
      p.stroke(0);
      p.strokeWeight(2);
      p.rect(10.0, 10.0, currentSize.contents.width - 20 | 0, currentSize.contents.height - 20 | 0);
      p.stroke(0, 0, 0);
      p.strokeWeight(1);
      p.noFill();
      var centerX = currentSize.contents.width / 2.0;
      var centerY = currentSize.contents.height / 2.0;
      var maxRadius = Math.min(centerX, centerY) - 50.0;
      for(var i = 1; i <= 20; ++i){
        var radius = maxRadius * i / 20;
        p.circle(centerX, centerY, radius * 2.0);
      }
      if (p.mouseX > 0.0 && p.mouseY > 0.0) {
        p.stroke(100, 150, 255);
        p.strokeWeight(1);
        p.line(centerX, centerY, p.mouseX, p.mouseY);
        p.circle(p.mouseX, p.mouseY, 20.0);
        return ;
      }
      
    });
}

((new p5(sketch)));

export {
  getPaperSize ,
  sketch ,
}
/*  Not a pure module */
