// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

var state = {
  contents: {
    currentP5: undefined,
    sketches: [],
    currentIndex: 0,
    isLoading: false
  }
};

function removeCurrentSketch() {
  console.log("removeCurrentSketch called");
  var sketchDiv = document.getElementById("sketch");
  if (sketchDiv == null) {
    console.log("Sketch container not found during removal");
  } else {
    console.log("Clearing sketch container innerHTML");
    sketchDiv.innerHTML = "";
  }
  var p5 = state.contents.currentP5;
  if (p5 !== undefined) {
    console.log("Calling p5.remove()");
    Caml_option.valFromOption(p5).remove();
    var init = state.contents;
    state.contents = {
      currentP5: undefined,
      sketches: init.sketches,
      currentIndex: init.currentIndex,
      isLoading: init.isLoading
    };
    return ;
  }
  console.log("No current p5 instance to remove");
}

function switchToSketch(index) {
  console.log("=== Switching to sketch index: " + index.toString() + " ===");
  removeCurrentSketch();
  var init = state.contents;
  state.contents = {
    currentP5: init.currentP5,
    sketches: init.sketches,
    currentIndex: index,
    isLoading: true
  };
  var config = state.contents.sketches[index];
  if (config !== undefined) {
    console.log("Dynamically loading sketch: " + config.name);
    (((function(loader, sketchName) {
          Promise.all([
            loader(),
            import('p5')
          ])
            .then(([sketchModule, p5Module]) => {
              console.log('Sketch module loaded:', sketchName);
              const p5Constructor = p5Module.default;
              const sketchFn = sketchModule.createSketch();
              const p5Instance = new p5Constructor(sketchFn, 'sketch');

              // Update state with loaded sketch
              window.__currentP5Instance = p5Instance;
              //-- @TODO fix
              // state := {
              //         ...state.contents,
              //         currentP5: Some(p5Instance),
              //         currentIndex: index,
              //       }
              window.__sketchLoadComplete = true;
            })
            .catch(err => {
              console.error('Failed to load sketch:', err);
              window.__sketchLoadError = err;
            });
        }))(config.loader, config.name));
    return ((function checkLoaded() {
          if (window.__sketchLoadComplete) {
            window.__sketchLoadComplete = false;
            return;
          }
          if (window.__sketchLoadError) {
            window.__sketchLoadError = null;
            return;
          }
          setTimeout(checkLoaded, 50);
        })());
  }
  console.log("Sketch at index " + index.toString() + " not found");
  var init$1 = state.contents;
  state.contents = {
    currentP5: init$1.currentP5,
    sketches: init$1.sketches,
    currentIndex: init$1.currentIndex,
    isLoading: false
  };
}

function createSketchSelector() {
  var controlsDiv = document.getElementById("sketch-controls");
  if (controlsDiv == null) {
    console.log("Controls container not found");
    return ;
  }
  controlsDiv.innerHTML = "";
  var label = document.createElement("label");
  label.textContent = "Select Sketch: ";
  label.className = "sketch-label";
  controlsDiv.appendChild(label);
  var select = document.createElement("select");
  select.className = "sketch-selector";
  state.contents.sketches.forEach(function (sketch, index) {
        var option = document.createElement("option");
        option.value = index.toString();
        option.textContent = sketch.name;
        select.appendChild(option);
      });
  select.value = state.contents.currentIndex.toString();
  select.addEventListener("change", (function () {
          var selectedIndex = Core__Option.getOr(Core__Int.fromString(select.value, undefined), 0);
          console.log("Dropdown changed to index: " + selectedIndex.toString());
          switchToSketch(selectedIndex);
        }));
  controlsDiv.appendChild(select);
  console.log("Sketch selector created");
}

function exportCurrentSketch() {
  var p5 = window.__currentP5Instance;
  var formatSelect = document.getElementById("export-format");
  if (formatSelect == null) {
    console.log("Export format selector not found");
    return ;
  }
  var format = formatSelect.value;
  console.log("Exporting current sketch as " + format);
  var canvas = p5.canvas;
  var timestamp = new Date().toISOString();
  var filename = timestamp + "." + format;
  if (format === "png") {
    var dataUrl = canvas.toDataURL("image/png", 1.0);
    var link = document.createElement("a");
    link.href = dataUrl;
    link.download = filename;
    var linkStyle = link.style;
    linkStyle.display = "none";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    return ;
  }
  if (format !== "svg") {
    return ;
  }
  var svgElements = document.getElementsByTagName("svg");
  var svgElement = svgElements[0];
  if (svgElement !== undefined) {
    var paperSize = PlotterFrame.getCurrentPaperSize();
    var svgContent = Caml_option.valFromOption(svgElement).outerHTML;
    var svgTagRegex = new RegExp("<svg([^>]*)>");
    var enhancedSvg = svgContent.replace(svgTagRegex, (function (attrs) {
            var viewBoxRegex = new RegExp("viewBox=\"([^\"]+)\"");
            var viewBoxMatch = attrs.match(viewBoxRegex);
            var viewBoxAttr;
            if (viewBoxMatch == null) {
              viewBoxAttr = "";
            } else {
              var vb = viewBoxMatch[1];
              viewBoxAttr = vb !== undefined ? " viewBox=\"" + vb + "\"" : "";
            }
            var widthMmStr = paperSize.widthMm.toString();
            var heightMmStr = paperSize.heightMm.toString();
            return "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"" + widthMmStr + "mm\" height=\"" + heightMmStr + "mm\"" + viewBoxAttr + ">";
          }));
    var blob = new Blob([enhancedSvg], {
          type: "image/svg+xml"
        });
    var url = URL.createObjectURL(blob);
    var link$1 = document.createElement("a");
    link$1.href = url;
    link$1.download = filename;
    var linkStyle$1 = link$1.style;
    linkStyle$1.display = "none";
    document.body.appendChild(link$1);
    link$1.click();
    document.body.removeChild(link$1);
    setTimeout((function () {
            URL.revokeObjectURL(url);
          }), 100);
    console.log("Saved SVG: " + filename + " (" + paperSize.widthMm.toString() + "mm × " + paperSize.heightMm.toString() + "mm)");
    return ;
  }
  console.log("No SVG element found - canvas is not using SVG renderer");
  console.log("SVG export requires creating canvas with SVG renderer");
}

function registerSketch(name, loader) {
  var init = state.contents;
  state.contents = {
    currentP5: init.currentP5,
    sketches: state.contents.sketches.concat([{
            name: name,
            loader: loader
          }]),
    currentIndex: init.currentIndex,
    isLoading: init.isLoading
  };
  console.log("Registered sketch: " + name);
}

function init() {
  console.log("Initializing Sketch Manager...");
  createSketchSelector();
  var exportBtn = document.getElementById("export-btn");
  if (exportBtn == null) {
    console.log("Export button not found");
  } else {
    exportBtn.addEventListener("click", (function () {
            exportCurrentSketch();
          }));
    console.log("Export button initialized");
  }
  if (state.contents.sketches.length > 0) {
    switchToSketch(0);
  }
  console.log("Sketch Manager initialized");
}

export {
  state ,
  removeCurrentSketch ,
  switchToSketch ,
  createSketchSelector ,
  exportCurrentSketch ,
  registerSketch ,
  init ,
}
/* PlotterFrame Not a pure module */
