// Generated by ReScript, PLEASE EDIT WITH CARE

import P5 from "p5";
import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

var state = {
  contents: {
    currentP5: undefined,
    sketches: [],
    currentIndex: 0
  }
};

function removeCurrentSketch() {
  console.log("removeCurrentSketch called");
  var sketchDiv = document.getElementById("sketch");
  if (sketchDiv == null) {
    console.log("Sketch container not found during removal");
  } else {
    console.log("Clearing sketch container innerHTML");
    sketchDiv.innerHTML = "";
  }
  var p5 = state.contents.currentP5;
  if (p5 !== undefined) {
    console.log("Calling p5.remove()");
    Caml_option.valFromOption(p5).remove();
    var init = state.contents;
    state.contents = {
      currentP5: undefined,
      sketches: init.sketches,
      currentIndex: init.currentIndex
    };
    return ;
  }
  console.log("No current p5 instance to remove");
}

function switchToSketch(index) {
  console.log("=== Switching to sketch index: " + index.toString() + " ===");
  removeCurrentSketch();
  ((setTimeout(() => {}, 10)));
  var config = state.contents.sketches[index];
  if (config !== undefined) {
    console.log("Creating new sketch: " + config.name);
    var sketchFn = config.createFn();
    var p5Instance = new P5(sketchFn, "sketch");
    console.log("New sketch attached to container");
    var init = state.contents;
    state.contents = {
      currentP5: Caml_option.some(p5Instance),
      sketches: init.sketches,
      currentIndex: index
    };
    console.log("=== Sketch switch complete ===");
    return ;
  }
  console.log("Sketch at index " + index.toString() + " not found");
}

function createSketchSelector() {
  var controlsDiv = document.getElementById("sketch-controls");
  if (controlsDiv == null) {
    console.log("Controls container not found");
    return ;
  }
  controlsDiv.innerHTML = "";
  var label = document.createElement("label");
  label.textContent = "Select Sketch: ";
  label.className = "sketch-label";
  controlsDiv.appendChild(label);
  var select = document.createElement("select");
  select.className = "sketch-selector";
  state.contents.sketches.forEach(function (sketch, index) {
        var option = document.createElement("option");
        option.value = index.toString();
        option.textContent = sketch.name;
        select.appendChild(option);
      });
  select.value = state.contents.currentIndex.toString();
  select.addEventListener("change", (function () {
          var selectedIndex = Core__Option.getOr(Core__Int.fromString(select.value, undefined), 0);
          console.log("Dropdown changed to index: " + selectedIndex.toString());
          switchToSketch(selectedIndex);
        }));
  controlsDiv.appendChild(select);
  console.log("Sketch selector created");
}

function registerSketch(name, createFn) {
  var init = state.contents;
  state.contents = {
    currentP5: init.currentP5,
    sketches: state.contents.sketches.concat([{
            name: name,
            createFn: createFn
          }]),
    currentIndex: init.currentIndex
  };
  console.log("Registered sketch: " + name);
}

function init() {
  console.log("Initializing Sketch Manager...");
  createSketchSelector();
  if (state.contents.sketches.length > 0) {
    switchToSketch(0);
  }
  console.log("Sketch Manager initialized");
}

export {
  state ,
  removeCurrentSketch ,
  switchToSketch ,
  createSketchSelector ,
  registerSketch ,
  init ,
}
/* p5 Not a pure module */
