// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PlotterFrame from "./PlotterFrame.res.mjs";

function drawTile(p, _x, _y, _size, _l) {
  while(true) {
    var l = _l;
    var size = _size;
    var y = _y;
    var x = _x;
    console.log(l);
    if (l === 0) {
      var orientation = p.random(0.0, 2.0) | 0;
      var centerX = x + size / 2.0;
      var centerY = y + size / 2.0;
      var lineLength = size * 0.5;
      p.stroke(0);
      p.strokeWeight(1);
      if (orientation === 0) {
        var lineTop = centerY - lineLength / 2.0;
        var lineBottom = centerY + lineLength / 2.0;
        p.line(centerX, lineTop, centerX, lineBottom);
        return ;
      }
      var lineLeft = centerX - lineLength / 2.0;
      var lineRight = centerX + lineLength / 2.0;
      p.line(lineLeft, centerY, lineRight, centerY);
      return ;
    }
    var s = size / 2.0;
    var nextlevel = l - 1 | 0;
    drawTile(p, x, y, s, nextlevel);
    drawTile(p, x + s, y, s, nextlevel);
    drawTile(p, x, y + s, s, nextlevel);
    _l = nextlevel;
    _size = s;
    _y = y + s;
    _x = x + s;
    continue ;
  };
}

var hasDrawn = {
  contents: false
};

function draw(p, paper) {
  if (hasDrawn.contents) {
    return ;
  }
  var paperWidth = paper.width;
  var paperHeight = paper.height;
  var size = paperWidth < paperHeight ? paperWidth : paperHeight;
  drawTile(p, 0.0, 0.0, size, 1);
  p.noLoop();
  hasDrawn.contents = true;
}

var createSketch = PlotterFrame.createPlotterSketch(draw);

var tileSize = 50.0;

export {
  tileSize ,
  drawTile ,
  hasDrawn ,
  draw ,
  createSketch ,
}
/* createSketch Not a pure module */
