// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

var currentLevel = {
  contents: 4
};

var showDebugGrid = {
  contents: false
};

var currentTileType = {
  contents: "Straight"
};

function drawWavyLine(p, x1, y1, x2, y2, isVertical) {
  if (isVertical) {
    var amplitude = (x2 - x1) * 0.2;
    var centerX = (x1 + x2) / 2.0;
    for(var i = 0; i <= 50; ++i){
      var t = i / 50;
      var y = y1 + (y2 - y1) * t;
      var wave = Math.sin(t * 2.0 * Math.PI * 2.0) * amplitude;
      var x = centerX + wave;
      if (i !== 0) {
        var prevT = (i - 1 | 0) / 50;
        var prevY = y1 + (y2 - y1) * prevT;
        var prevWave = Math.sin(prevT * 2.0 * Math.PI * 2.0) * amplitude;
        var prevX = centerX + prevWave;
        p.line(prevX, prevY, x, y);
      }
      
    }
    return ;
  }
  var amplitude$1 = (y2 - y1) * 0.2;
  var centerY = (y1 + y2) / 2.0;
  for(var i$1 = 0; i$1 <= 50; ++i$1){
    var t$1 = i$1 / 50;
    var x$1 = x1 + (x2 - x1) * t$1;
    var wave$1 = Math.sin(t$1 * 2.0 * Math.PI * 2.0) * amplitude$1;
    var y$1 = centerY + wave$1;
    if (i$1 !== 0) {
      var prevT$1 = (i$1 - 1 | 0) / 50;
      var prevX$1 = x1 + (x2 - x1) * prevT$1;
      var prevWave$1 = Math.sin(prevT$1 * 2.0 * Math.PI * 2.0) * amplitude$1;
      var prevY$1 = centerY + prevWave$1;
      p.line(prevX$1, prevY$1, x$1, y$1);
    }
    
  }
}

function drawNoisyWave(p, x1, y1, x2, y2, isVertical) {
  var noiseOffset = (x1 + y1) * 0.01;
  if (isVertical) {
    var amplitude = (x2 - x1) * 0.3;
    var centerX = (x1 + x2) / 2.0;
    for(var i = 0; i <= 100; ++i){
      var t = i / 100;
      var y = y1 + (y2 - y1) * t;
      var noiseVal = p.noise(t * 3.0 + noiseOffset);
      var wave = (noiseVal - 0.5) * 2.0 * amplitude;
      var x = centerX + wave;
      if (i !== 0) {
        var prevT = (i - 1 | 0) / 100;
        var prevY = y1 + (y2 - y1) * prevT;
        var prevNoiseVal = p.noise(prevT * 3.0 + noiseOffset);
        var prevWave = (prevNoiseVal - 0.5) * 2.0 * amplitude;
        var prevX = centerX + prevWave;
        p.line(prevX, prevY, x, y);
      }
      
    }
    return ;
  }
  var amplitude$1 = (y2 - y1) * 0.3;
  var centerY = (y1 + y2) / 2.0;
  for(var i$1 = 0; i$1 <= 100; ++i$1){
    var t$1 = i$1 / 100;
    var x$1 = x1 + (x2 - x1) * t$1;
    var noiseVal$1 = p.noise(t$1 * 3.0 + noiseOffset);
    var wave$1 = (noiseVal$1 - 0.5) * 2.0 * amplitude$1;
    var y$1 = centerY + wave$1;
    if (i$1 !== 0) {
      var prevT$1 = (i$1 - 1 | 0) / 100;
      var prevX$1 = x1 + (x2 - x1) * prevT$1;
      var prevNoiseVal$1 = p.noise(prevT$1 * 3.0 + noiseOffset);
      var prevWave$1 = (prevNoiseVal$1 - 0.5) * 2.0 * amplitude$1;
      var prevY$1 = centerY + prevWave$1;
      p.line(prevX$1, prevY$1, x$1, y$1);
    }
    
  }
}

function drawTile(p, _x, _y, _size, _l, canvasWidth, canvasHeight) {
  while(true) {
    var l = _l;
    var size = _size;
    var y = _y;
    var x = _x;
    console.log(l);
    if (x >= canvasWidth || y >= canvasHeight || x + size <= 0.0 || y + size <= 0.0) {
      return ;
    }
    if (showDebugGrid.contents) {
      var visibleLeft = x > 0.0 ? x : 0.0;
      var visibleTop = y > 0.0 ? y : 0.0;
      var visibleRight = x + size < canvasWidth ? x + size : canvasWidth;
      var visibleBottom = y + size < canvasHeight ? y + size : canvasHeight;
      var visibleWidth = visibleRight - visibleLeft;
      var visibleHeight = visibleBottom - visibleTop;
      p.stroke(255, 0, 0);
      p.strokeWeight(1);
      p.noFill();
      p.rect(visibleLeft, visibleTop, visibleWidth, visibleHeight);
    }
    if (l === 0) {
      var orientation = p.random(0.0, 2.0) | 0;
      p.stroke(0);
      p.strokeWeight(1);
      p.noFill();
      var visibleLeft$1 = x > 0.0 ? x : 0.0;
      var visibleRight$1 = x + size < canvasWidth ? x + size : canvasWidth;
      var visibleTop$1 = y > 0.0 ? y : 0.0;
      var visibleBottom$1 = y + size < canvasHeight ? y + size : canvasHeight;
      if (orientation === 0) {
        var match = currentTileType.contents;
        switch (match) {
          case "Straight" :
              var centerX = (visibleLeft$1 + visibleRight$1) / 2.0;
              p.line(centerX, visibleTop$1, centerX, visibleBottom$1);
              return ;
          case "Wavy" :
              return drawWavyLine(p, visibleLeft$1, visibleTop$1, visibleRight$1, visibleBottom$1, true);
          case "Noisy" :
              return drawNoisyWave(p, visibleLeft$1, visibleTop$1, visibleRight$1, visibleBottom$1, true);
          
        }
      } else {
        var match$1 = currentTileType.contents;
        switch (match$1) {
          case "Straight" :
              var centerY = (visibleTop$1 + visibleBottom$1) / 2.0;
              p.line(visibleLeft$1, centerY, visibleRight$1, centerY);
              return ;
          case "Wavy" :
              return drawWavyLine(p, visibleLeft$1, visibleTop$1, visibleRight$1, visibleBottom$1, false);
          case "Noisy" :
              return drawNoisyWave(p, visibleLeft$1, visibleTop$1, visibleRight$1, visibleBottom$1, false);
          
        }
      }
    } else {
      var s = size / 2.0;
      var nextlevel = l - 1 | 0;
      drawTile(p, x, y, s, nextlevel, canvasWidth, canvasHeight);
      drawTile(p, x + s, y, s, nextlevel, canvasWidth, canvasHeight);
      drawTile(p, x, y + s, s, nextlevel, canvasWidth, canvasHeight);
      _l = nextlevel;
      _size = s;
      _y = y + s;
      _x = x + s;
      continue ;
    }
  };
}

var p5Instance = {
  contents: undefined
};

var paperSize = {
  contents: undefined
};

function redrawTiling() {
  var p = p5Instance.contents;
  if (p !== undefined) {
    Caml_option.valFromOption(p).loop();
    return ;
  }
  
}

function draw(p, paper) {
  p5Instance.contents = Caml_option.some(p);
  paperSize.contents = paper;
  var paperWidth = paper.width;
  var paperHeight = paper.height;
  var size = paperWidth > paperHeight ? paperWidth : paperHeight;
  var offsetX = (size - paperWidth) / 2.0;
  var offsetY = (size - paperHeight) / 2.0;
  drawTile(p, - offsetX, - offsetY, size, currentLevel.contents, paperWidth, paperHeight);
  p.noLoop();
}

var controlsCreated = {
  contents: false
};

function setupControls(p) {
  if (controlsCreated.contents) {
    return ;
  }
  controlsCreated.contents = true;
  var controlsDiv = document.getElementById("paper-settings-controls");
  if (controlsDiv == null) {
    console.log("Paper settings controls container not found");
  } else {
    var levelLabel = document.createElement("label");
    levelLabel.textContent = "Recursion Level (0-8)";
    levelLabel.setAttribute("for", "recursion-level");
    levelLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
    controlsDiv.appendChild(levelLabel);
    var levelInput = document.createElement("input");
    levelInput.setAttribute("type", "number");
    levelInput.setAttribute("id", "recursion-level");
    levelInput.value = "4";
    levelInput.setAttribute("min", "0");
    levelInput.setAttribute("max", "8");
    levelInput.setAttribute("step", "1");
    levelInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
    levelInput.addEventListener("input", (function () {
            var value = Core__Option.getOr(Core__Float.fromString(levelInput.value), 4.0);
            currentLevel.contents = value | 0;
            redrawTiling();
          }));
    controlsDiv.appendChild(levelInput);
    var tileTypeLabel = document.createElement("label");
    tileTypeLabel.textContent = "Line Type";
    tileTypeLabel.setAttribute("for", "tile-type");
    tileTypeLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
    controlsDiv.appendChild(tileTypeLabel);
    var tileTypeSelect = document.createElement("select");
    tileTypeSelect.setAttribute("id", "tile-type");
    tileTypeSelect.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
    var straightOption = document.createElement("option");
    straightOption.value = "straight";
    straightOption.textContent = "Straight Lines";
    tileTypeSelect.appendChild(straightOption);
    var wavyOption = document.createElement("option");
    wavyOption.value = "wavy";
    wavyOption.textContent = "Wavy Lines (Sin Wave)";
    tileTypeSelect.appendChild(wavyOption);
    var noisyOption = document.createElement("option");
    noisyOption.value = "noisy";
    noisyOption.textContent = "Noisy Waves (Random Amplitude)";
    tileTypeSelect.appendChild(noisyOption);
    tileTypeSelect.addEventListener("change", (function () {
            var value = tileTypeSelect.value;
            currentTileType.contents = value === "wavy" ? "Wavy" : (
                value === "noisy" ? "Noisy" : "Straight"
              );
            redrawTiling();
          }));
    controlsDiv.appendChild(tileTypeSelect);
    var debugLabel = document.createElement("label");
    debugLabel.className = "flex items-center mt-3 cursor-pointer";
    var debugCheckbox = document.createElement("input");
    debugCheckbox.setAttribute("type", "checkbox");
    debugCheckbox.setAttribute("id", "debug-grid");
    debugCheckbox.className = "mr-2";
    debugCheckbox.addEventListener("change", (function () {
            showDebugGrid.contents = !showDebugGrid.contents;
            redrawTiling();
          }));
    debugLabel.appendChild(debugCheckbox);
    var debugText = document.createElement("span");
    debugText.textContent = "Show Debug Grid (red)";
    debugText.className = "text-sm text-zinc-300";
    debugLabel.appendChild(debugText);
    controlsDiv.appendChild(debugLabel);
    var hintLabel = document.createElement("p");
    hintLabel.textContent = "Click canvas to regenerate pattern";
    hintLabel.className = "text-xs text-zinc-400 mt-3 italic";
    controlsDiv.appendChild(hintLabel);
    console.log("Tiling controls created");
  }
  var canvas = p.canvas;
  canvas.addEventListener("click", (function () {
          var p = p5Instance.contents;
          if (p !== undefined) {
            Caml_option.valFromOption(p).randomSeed(Date.now());
            return redrawTiling();
          }
          
        }));
}

function drawWithControls(p, paper) {
  setupControls(p);
  draw(p, paper);
}

var createSketch = PlotterFrame.createPlotterSketch(drawWithControls);

var tileSize = 50.0;

export {
  tileSize ,
  currentLevel ,
  showDebugGrid ,
  currentTileType ,
  drawWavyLine ,
  drawNoisyWave ,
  drawTile ,
  p5Instance ,
  paperSize ,
  redrawTiling ,
  draw ,
  controlsCreated ,
  setupControls ,
  drawWithControls ,
  createSketch ,
}
/* createSketch Not a pure module */
