// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

function drawTile(p, _x, _y, _size, _l, canvasWidth, canvasHeight) {
  while(true) {
    var l = _l;
    var size = _size;
    var y = _y;
    var x = _x;
    console.log(l);
    if (x >= canvasWidth || y >= canvasHeight || x + size <= 0.0 || y + size <= 0.0) {
      return ;
    }
    var visibleLeft = x > 0.0 ? x : 0.0;
    var visibleTop = y > 0.0 ? y : 0.0;
    var visibleRight = x + size < canvasWidth ? x + size : canvasWidth;
    var visibleBottom = y + size < canvasHeight ? y + size : canvasHeight;
    var visibleWidth = visibleRight - visibleLeft;
    var visibleHeight = visibleBottom - visibleTop;
    p.stroke(255, 0, 0);
    p.strokeWeight(1);
    p.noFill();
    p.rect(visibleLeft, visibleTop, visibleWidth, visibleHeight);
    if (l === 0) {
      var orientation = p.random(0.0, 2.0) | 0;
      p.stroke(0);
      p.strokeWeight(1);
      if (orientation === 0) {
        var visibleLeft$1 = x > 0.0 ? x : 0.0;
        var visibleRight$1 = x + size < canvasWidth ? x + size : canvasWidth;
        var visibleTop$1 = y > 0.0 ? y : 0.0;
        var visibleBottom$1 = y + size < canvasHeight ? y + size : canvasHeight;
        var centerX = (visibleLeft$1 + visibleRight$1) / 2.0;
        p.line(centerX, visibleTop$1, centerX, visibleBottom$1);
        return ;
      }
      var visibleLeft$2 = x > 0.0 ? x : 0.0;
      var visibleRight$2 = x + size < canvasWidth ? x + size : canvasWidth;
      var visibleTop$2 = y > 0.0 ? y : 0.0;
      var visibleBottom$2 = y + size < canvasHeight ? y + size : canvasHeight;
      var centerY = (visibleTop$2 + visibleBottom$2) / 2.0;
      p.line(visibleLeft$2, centerY, visibleRight$2, centerY);
      return ;
    }
    var s = size / 2.0;
    var nextlevel = l - 1 | 0;
    drawTile(p, x, y, s, nextlevel, canvasWidth, canvasHeight);
    drawTile(p, x + s, y, s, nextlevel, canvasWidth, canvasHeight);
    drawTile(p, x, y + s, s, nextlevel, canvasWidth, canvasHeight);
    _l = nextlevel;
    _size = s;
    _y = y + s;
    _x = x + s;
    continue ;
  };
}

var currentLevel = {
  contents: 4
};

var p5Instance = {
  contents: undefined
};

var paperSize = {
  contents: undefined
};

function redrawTiling() {
  var p = p5Instance.contents;
  if (p !== undefined) {
    Caml_option.valFromOption(p).loop();
    return ;
  }
  
}

function draw(p, paper) {
  p5Instance.contents = Caml_option.some(p);
  paperSize.contents = paper;
  var paperWidth = paper.width;
  var paperHeight = paper.height;
  var size = paperWidth > paperHeight ? paperWidth : paperHeight;
  var offsetX = (size - paperWidth) / 2.0;
  var offsetY = (size - paperHeight) / 2.0;
  drawTile(p, - offsetX, - offsetY, size, currentLevel.contents, paperWidth, paperHeight);
  p.noLoop();
}

var controlsCreated = {
  contents: false
};

function setupControls(p) {
  if (controlsCreated.contents) {
    return ;
  }
  controlsCreated.contents = true;
  var controlsDiv = document.getElementById("paper-settings-controls");
  if (controlsDiv == null) {
    console.log("Paper settings controls container not found");
  } else {
    var levelLabel = document.createElement("label");
    levelLabel.textContent = "Recursion Level (0-8)";
    levelLabel.setAttribute("for", "recursion-level");
    levelLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
    controlsDiv.appendChild(levelLabel);
    var levelInput = document.createElement("input");
    levelInput.setAttribute("type", "number");
    levelInput.setAttribute("id", "recursion-level");
    levelInput.value = "4";
    levelInput.setAttribute("min", "0");
    levelInput.setAttribute("max", "8");
    levelInput.setAttribute("step", "1");
    levelInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
    levelInput.addEventListener("input", (function () {
            var value = Core__Option.getOr(Core__Float.fromString(levelInput.value), 4.0);
            currentLevel.contents = value | 0;
            redrawTiling();
          }));
    controlsDiv.appendChild(levelInput);
    var hintLabel = document.createElement("p");
    hintLabel.textContent = "Click canvas to regenerate pattern";
    hintLabel.className = "text-xs text-zinc-400 mt-3 italic";
    controlsDiv.appendChild(hintLabel);
    console.log("Tiling controls created");
  }
  var canvas = p.canvas;
  canvas.addEventListener("click", (function () {
          var p = p5Instance.contents;
          if (p !== undefined) {
            Caml_option.valFromOption(p).randomSeed(Date.now());
            return redrawTiling();
          }
          
        }));
}

function drawWithControls(p, paper) {
  setupControls(p);
  draw(p, paper);
}

var createSketch = PlotterFrame.createPlotterSketch(drawWithControls);

var tileSize = 50.0;

export {
  tileSize ,
  drawTile ,
  currentLevel ,
  p5Instance ,
  paperSize ,
  redrawTiling ,
  draw ,
  controlsCreated ,
  setupControls ,
  drawWithControls ,
  createSketch ,
}
/* createSketch Not a pure module */
