// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

var tileSize = {
  contents: 20
};

var imageBaseUrl = {
  contents: "https://placecats.com"
};

var loadedImage = {
  contents: undefined
};

var p5Instance = {
  contents: undefined
};

var paperSize = {
  contents: undefined
};

function drawWavyVertical(p, x, y, size) {
  var amplitude = size * 0.15;
  var centerX = x + size / 2.0;
  for(var i = 0; i <= 20; ++i){
    if (i > 0) {
      var t = i / 20;
      var prevT = (i - 1 | 0) / 20;
      var yPos = y + t * size;
      var prevY = y + prevT * size;
      var wave = Math.sin(t * 2.0 * Math.PI * 2.0) * amplitude;
      var prevWave = Math.sin(prevT * 2.0 * Math.PI * 2.0) * amplitude;
      var xPos = centerX + wave;
      var prevX = centerX + prevWave;
      p.line(prevX, prevY, xPos, yPos);
    }
    
  }
}

function drawWavyHorizontal(p, x, y, size) {
  var amplitude = size * 0.15;
  var centerY = y + size / 2.0;
  for(var i = 0; i <= 20; ++i){
    if (i > 0) {
      var t = i / 20;
      var prevT = (i - 1 | 0) / 20;
      var xPos = x + t * size;
      var prevX = x + prevT * size;
      var wave = Math.sin(t * 2.0 * Math.PI * 2.0) * amplitude;
      var prevWave = Math.sin(prevT * 2.0 * Math.PI * 2.0) * amplitude;
      var yPos = centerY + wave;
      var prevY = centerY + prevWave;
      p.line(prevX, prevY, xPos, yPos);
    }
    
  }
}

function drawTileForBrightness(p, x, y, size, brightness) {
  if (brightness < 64.0) {
    drawWavyVertical(p, x, y, size);
    drawWavyVertical(p, x + size / 2.0, y, size / 2.0);
    drawWavyHorizontal(p, x, y, size);
    return drawWavyHorizontal(p, x, y + size / 2.0, size);
  }
  if (brightness < 128.0) {
    drawWavyVertical(p, x, y, size);
    return drawWavyHorizontal(p, x, y, size);
  }
  if (brightness >= 192.0) {
    return ;
  }
  var gridX = x / size | 0;
  var gridY = y / size | 0;
  if ((gridX + gridY | 0) % 2 === 0) {
    return drawWavyVertical(p, x, y, size);
  } else {
    return drawWavyHorizontal(p, x, y, size);
  }
}

function draw(p, paper) {
  p5Instance.contents = Caml_option.some(p);
  paperSize.contents = paper;
  p.background(255);
  p.stroke(0);
  p.strokeWeight(1);
  p.noFill();
  var img = loadedImage.contents;
  if (img !== undefined) {
    var img$1 = Caml_option.valFromOption(img);
    var paperWidth = paper.width;
    var paperHeight = paper.height;
    var tileSizeFloat = tileSize.contents;
    var cols = paperWidth / tileSizeFloat | 0;
    var rows = paperHeight / tileSizeFloat | 0;
    var imgWidth = img$1.width;
    var imgHeight = img$1.height;
    for(var row = 0; row < rows; ++row){
      for(var col = 0; col < cols; ++col){
        var x = col * tileSizeFloat;
        var y = row * tileSizeFloat;
        var imgX = col / cols * imgWidth | 0;
        var imgY = row / rows * imgHeight | 0;
        var pixel = img$1.get(imgX, imgY);
        var brightness = p.brightness(pixel);
        drawTileForBrightness(p, x, y, tileSizeFloat, brightness);
      }
    }
  } else {
    p.stroke(200);
    var paperWidth$1 = paper.width;
    var paperHeight$1 = paper.height;
    p.line(paperWidth$1 / 2.0 - 50.0, paperHeight$1 / 2.0, paperWidth$1 / 2.0 + 50.0, paperHeight$1 / 2.0);
  }
  p.noLoop();
}

function redraw() {
  var p = p5Instance.contents;
  if (p !== undefined) {
    Caml_option.valFromOption(p).loop();
    return ;
  }
  
}

function loadImageFromUrl(p, url) {
  console.log("Loading image from: " + url);
  var preview = document.getElementById("image-preview");
  if (!(preview == null)) {
    preview.setAttribute("src", url);
  }
  p.loadImage(url, (function (img) {
          loadedImage.contents = Caml_option.some(img);
          console.log("Image loaded successfully");
          redraw();
        }));
}

var controlsCreated = {
  contents: false
};

function setupControls(p) {
  if (controlsCreated.contents) {
    return ;
  }
  controlsCreated.contents = true;
  var controlsDiv = document.getElementById("paper-settings-controls");
  if (controlsDiv == null) {
    console.log("Paper settings controls container not found");
    return ;
  }
  var tileSizeLabel = document.createElement("label");
  tileSizeLabel.textContent = "Tile Size (pixels)";
  tileSizeLabel.setAttribute("for", "tile-size");
  tileSizeLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
  controlsDiv.appendChild(tileSizeLabel);
  var tileSizeInput = document.createElement("input");
  tileSizeInput.setAttribute("type", "number");
  tileSizeInput.setAttribute("id", "tile-size");
  tileSizeInput.value = "20";
  tileSizeInput.setAttribute("min", "5");
  tileSizeInput.setAttribute("max", "100");
  tileSizeInput.setAttribute("step", "5");
  tileSizeInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
  tileSizeInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Float.fromString(tileSizeInput.value), 15.0);
          tileSize.contents = value | 0;
          redraw();
        }));
  controlsDiv.appendChild(tileSizeInput);
  var previewLabel = document.createElement("label");
  previewLabel.textContent = "Image Preview";
  previewLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
  controlsDiv.appendChild(previewLabel);
  var previewImg = document.createElement("img");
  previewImg.setAttribute("id", "image-preview");
  PlotterFrame.setStyle(previewImg, "width", "100%");
  PlotterFrame.setStyle(previewImg, "border", "1px solid #52525b");
  PlotterFrame.setStyle(previewImg, "border-radius", "4px");
  PlotterFrame.setStyle(previewImg, "margin-bottom", "12px");
  controlsDiv.appendChild(previewImg);
  var urlLabel = document.createElement("label");
  urlLabel.textContent = "Image URL";
  urlLabel.setAttribute("for", "image-url");
  urlLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-3";
  controlsDiv.appendChild(urlLabel);
  var urlInput = document.createElement("input");
  urlInput.setAttribute("type", "text");
  urlInput.setAttribute("id", "image-url");
  urlInput.className = "w-full px-3 py-2 bg-zinc-700 border border-zinc-600 rounded-md text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
  controlsDiv.appendChild(urlInput);
  var loadButton = document.createElement("button");
  loadButton.textContent = "Load Image";
  loadButton.className = "w-full mt-2 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";
  loadButton.addEventListener("click", (function () {
          var url = urlInput.value;
          var urlParts = url.split("/");
          console.log(urlParts);
          if (urlParts.length >= 2) {
            var lastPart = Core__Option.getOr(urlParts[urlParts.length - 1 | 0], "");
            var secondLastPart = Core__Option.getOr(urlParts[urlParts.length - 2 | 0], "");
            var lastIsNumber = Core__Option.isSome(Core__Float.fromString(lastPart));
            var secondLastIsNumber = Core__Option.isSome(Core__Float.fromString(secondLastPart));
            if (lastIsNumber && secondLastIsNumber) {
              var baseUrlParts = urlParts.slice(0, urlParts.length - 2 | 0);
              var baseUrl = baseUrlParts.join("/");
              imageBaseUrl.contents = baseUrl;
              console.log("Updated base URL to: " + baseUrl);
            } else {
              imageBaseUrl.contents = url;
            }
          }
          var p = p5Instance.contents;
          if (p !== undefined) {
            return loadImageFromUrl(Caml_option.valFromOption(p), url);
          }
          
        }));
  controlsDiv.appendChild(loadButton);
  console.log("Wavy image controls created");
}

function buildImageUrl(baseUrl, paper) {
  var width = Js_math.ceil_int(0.25 * paper.width).toString();
  var height = Js_math.ceil_int(0.25 * paper.height).toString();
  var imageUrl = baseUrl + "/" + width + "/" + height;
  return "https://corsproxy.io/?" + imageUrl;
}

var lastPaperSize = {
  contents: undefined
};

function drawWithControls(p, paper) {
  setupControls(p);
  var lastPaper = lastPaperSize.contents;
  var paperSizeChanged = lastPaper !== undefined ? lastPaper.width !== paper.width || lastPaper.height !== paper.height : true;
  if (paperSizeChanged) {
    var newUrl = buildImageUrl(imageBaseUrl.contents, paper);
    var input = document.getElementById("image-url");
    if (!(input == null)) {
      input.value = newUrl;
    }
    loadImageFromUrl(p, newUrl);
    lastPaperSize.contents = paper;
  }
  draw(p, paper);
}

var createSketch = PlotterFrame.createPlotterSketch(drawWithControls);

export {
  tileSize ,
  imageBaseUrl ,
  loadedImage ,
  p5Instance ,
  paperSize ,
  drawWavyVertical ,
  drawWavyHorizontal ,
  drawTileForBrightness ,
  draw ,
  redraw ,
  loadImageFromUrl ,
  controlsCreated ,
  setupControls ,
  buildImageUrl ,
  lastPaperSize ,
  drawWithControls ,
  createSketch ,
}
/* createSketch Not a pure module */
