// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

var numLinesRef = {
  contents: 12
};

var amplitudeRef = {
  contents: 20.0
};

function draw(p, paper) {
  var numLines = numLinesRef.contents;
  var amplitude = amplitudeRef.contents;
  var centerY = paper.height / 2.0;
  var spacing = paper.height / (numLines + 1.0);
  for(var i = 1; i <= numLines; ++i){
    var y = spacing * i;
    var phaseShift = y < centerY ? Math.PI : 0.0;
    p.noFill();
    p.stroke(0);
    p.strokeWeight(2);
    p.push();
    p.beginShape();
    for(var step = 0; step <= 200; ++step){
      var t = step / 200;
      var x = t * paper.width;
      var waveOffset = Math.sin(t * 4.0 * 2.0 * Math.PI + phaseShift) * amplitude;
      p.vertex(x, y + waveOffset);
    }
    p.endShape();
    p.pop();
  }
}

function createControls() {
  var container = document.getElementById("sketch-specific-controls");
  if (container == null) {
    console.log("Sketch controls container not found");
    return ;
  }
  container.innerHTML = "";
  container.className = "space-y-4";
  var linesLabel = document.createElement("label");
  linesLabel.textContent = "Number of Lines";
  linesLabel.setAttribute("for", "num-lines");
  linesLabel.className = "block text-sm font-medium text-zinc-300 mb-1";
  container.appendChild(linesLabel);
  var linesInput = document.createElement("input");
  linesInput.setAttribute("type", "range");
  linesInput.setAttribute("id", "num-lines");
  linesInput.setAttribute("min", "3");
  linesInput.setAttribute("max", "30");
  linesInput.setAttribute("value", "12");
  linesInput.className = "w-full";
  container.appendChild(linesInput);
  var linesValue = document.createElement("div");
  linesValue.setAttribute("id", "num-lines-value");
  linesValue.textContent = "12";
  linesValue.className = "text-sm text-zinc-400";
  container.appendChild(linesValue);
  linesInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Int.fromString(linesInput.value, undefined), 12);
          numLinesRef.contents = value;
          linesValue.textContent = value.toString();
        }));
  var ampLabel = document.createElement("label");
  ampLabel.textContent = "Wave Amplitude";
  ampLabel.setAttribute("for", "amplitude");
  ampLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-4";
  container.appendChild(ampLabel);
  var ampInput = document.createElement("input");
  ampInput.setAttribute("type", "range");
  ampInput.setAttribute("id", "amplitude");
  ampInput.setAttribute("min", "5");
  ampInput.setAttribute("max", "100");
  ampInput.setAttribute("value", "20");
  ampInput.className = "w-full";
  container.appendChild(ampInput);
  var ampValue = document.createElement("div");
  ampValue.setAttribute("id", "amplitude-value");
  ampValue.textContent = "20";
  ampValue.className = "text-sm text-zinc-400";
  container.appendChild(ampValue);
  ampInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Float.fromString(ampInput.value), 20.0);
          amplitudeRef.contents = value;
          ampValue.textContent = value.toString();
        }));
  console.log("Wavy lines controls created");
}

function createSketch() {
  createControls();
  return PlotterFrame.createPlotterSketch(draw)();
}

export {
  numLinesRef ,
  amplitudeRef ,
  draw ,
  createControls ,
  createSketch ,
}
/* PlotterFrame Not a pure module */
