// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Int from "@rescript/core/src/Core__Int.res.mjs";
import * as Core__Float from "@rescript/core/src/Core__Float.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PlotterFrame from "./PlotterFrame.res.mjs";

var numLinesRef = {
  contents: 12
};

var amplitudeRef = {
  contents: 20.0
};

var gapSizeRef = {
  contents: 0.33
};

var frequencyRef = {
  contents: 4.0
};

var focalPointRef = {
  contents: undefined
};

var focalPointLockedRef = {
  contents: false
};

function draw(p, paper) {
  var numLines = numLinesRef.contents;
  var amplitude = amplitudeRef.contents;
  var gapSize = gapSizeRef.contents;
  var frequency = frequencyRef.contents;
  var centerYFixed = paper.height / 2.0;
  var match = focalPointRef.contents;
  var centerX = match !== undefined ? match[0] : paper.width / 2.0;
  var currentMarginMm = PlotterFrame.currentMarginMm.contents;
  var currentPaddingMm = PlotterFrame.currentPaddingMm.contents;
  var totalSpacePx = (currentMarginMm + currentPaddingMm) * 3.7795275591;
  var mouseXRaw = p.mouseX - totalSpacePx;
  var mouseYRaw = p.mouseY - totalSpacePx;
  if (!focalPointLockedRef.contents && mouseXRaw >= 0.0 && mouseXRaw <= paper.width && mouseYRaw >= 0.0 && mouseYRaw <= paper.height) {
    focalPointRef.contents = [
      mouseXRaw,
      centerYFixed
    ];
  } else if (!focalPointLockedRef.contents) {
    focalPointRef.contents = undefined;
  }
  var gapHeight = paper.height * gapSize;
  var gapTop = centerYFixed - gapHeight / 2.0;
  var linesPerSide = numLines / 2 | 0;
  for(var i = 1; i <= linesPerSide; ++i){
    var spacing = gapTop / (linesPerSide + 1.0);
    var baseY = spacing * i;
    var topPoints = [];
    p.noFill();
    p.stroke(0);
    p.strokeWeight(2);
    p.push();
    p.beginShape();
    for(var step = 0; step <= 200; ++step){
      var t = step / 200;
      var x = t * paper.width;
      var sineWave = Math.sin(t * frequency * 2.0 * Math.PI);
      var waveOffset = sineWave * amplitude;
      var dx = centerX - x;
      var dy = centerYFixed - baseY;
      var angleToCenter = Math.atan2(dy, dx);
      var xPull = sineWave * amplitude * Math.cos(angleToCenter) * 0.3;
      var yPull = sineWave * amplitude * Math.sin(angleToCenter) * 0.3;
      var finalX = x + xPull;
      var finalY = baseY + waveOffset + yPull;
      topPoints.push([
            finalX,
            finalY
          ]);
      p.vertex(finalX, finalY);
    }
    p.endShape();
    p.pop();
    p.push();
    p.beginShape();
    topPoints.forEach(function (param) {
          var mirroredY = centerYFixed + (centerYFixed - param[1]);
          p.vertex(param[0], mirroredY);
        });
    p.endShape();
    p.pop();
  }
  p.push();
  p.noFill();
  p.stroke(255, 0, 0);
  p.strokeWeight(2);
  p.circle(centerX, centerYFixed, 10.0);
  p.line(centerX - 5.0, centerYFixed, centerX + 5.0, centerYFixed);
  p.line(centerX, centerYFixed - 5.0, centerX, centerYFixed + 5.0);
  p.pop();
}

function createControls() {
  var container = document.getElementById("sketch-specific-controls");
  if (container == null) {
    console.log("Sketch controls container not found");
    return ;
  }
  container.innerHTML = "";
  container.className = "space-y-4";
  var linesLabel = document.createElement("label");
  linesLabel.textContent = "Number of Lines";
  linesLabel.setAttribute("for", "num-lines");
  linesLabel.className = "block text-sm font-medium text-zinc-300 mb-1";
  container.appendChild(linesLabel);
  var linesInput = document.createElement("input");
  linesInput.setAttribute("type", "range");
  linesInput.setAttribute("id", "num-lines");
  linesInput.setAttribute("min", "3");
  linesInput.setAttribute("max", "30");
  linesInput.setAttribute("value", "12");
  linesInput.className = "w-full";
  container.appendChild(linesInput);
  var linesValue = document.createElement("div");
  linesValue.setAttribute("id", "num-lines-value");
  linesValue.textContent = "12";
  linesValue.className = "text-sm text-zinc-400";
  container.appendChild(linesValue);
  linesInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Int.fromString(linesInput.value, undefined), 12);
          numLinesRef.contents = value;
          linesValue.textContent = value.toString();
        }));
  var ampLabel = document.createElement("label");
  ampLabel.textContent = "Wave Amplitude";
  ampLabel.setAttribute("for", "amplitude");
  ampLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-4";
  container.appendChild(ampLabel);
  var ampInput = document.createElement("input");
  ampInput.setAttribute("type", "range");
  ampInput.setAttribute("id", "amplitude");
  ampInput.setAttribute("min", "5");
  ampInput.setAttribute("max", "100");
  ampInput.setAttribute("value", "20");
  ampInput.className = "w-full";
  container.appendChild(ampInput);
  var ampValue = document.createElement("div");
  ampValue.setAttribute("id", "amplitude-value");
  ampValue.textContent = "20";
  ampValue.className = "text-sm text-zinc-400";
  container.appendChild(ampValue);
  ampInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Float.fromString(ampInput.value), 20.0);
          amplitudeRef.contents = value;
          ampValue.textContent = value.toString();
        }));
  var gapLabel = document.createElement("label");
  gapLabel.textContent = "Center Gap Size (%)";
  gapLabel.setAttribute("for", "gap-size");
  gapLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-4";
  container.appendChild(gapLabel);
  var gapInput = document.createElement("input");
  gapInput.setAttribute("type", "range");
  gapInput.setAttribute("id", "gap-size");
  gapInput.setAttribute("min", "0");
  gapInput.setAttribute("max", "50");
  gapInput.setAttribute("value", "33");
  gapInput.className = "w-full";
  container.appendChild(gapInput);
  var gapValue = document.createElement("div");
  gapValue.setAttribute("id", "gap-size-value");
  gapValue.textContent = "33%";
  gapValue.className = "text-sm text-zinc-400";
  container.appendChild(gapValue);
  gapInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Float.fromString(gapInput.value), 33.0);
          gapSizeRef.contents = value / 100.0;
          gapValue.textContent = value.toString() + "%";
        }));
  var freqLabel = document.createElement("label");
  freqLabel.textContent = "Wave Frequency";
  freqLabel.setAttribute("for", "frequency");
  freqLabel.className = "block text-sm font-medium text-zinc-300 mb-1 mt-4";
  container.appendChild(freqLabel);
  var freqInput = document.createElement("input");
  freqInput.setAttribute("type", "range");
  freqInput.setAttribute("id", "frequency");
  freqInput.setAttribute("min", "1");
  freqInput.setAttribute("max", "20");
  freqInput.setAttribute("value", "4");
  freqInput.className = "w-full";
  container.appendChild(freqInput);
  var freqValue = document.createElement("div");
  freqValue.setAttribute("id", "frequency-value");
  freqValue.textContent = "4";
  freqValue.className = "text-sm text-zinc-400";
  container.appendChild(freqValue);
  freqInput.addEventListener("input", (function () {
          var value = Core__Option.getOr(Core__Float.fromString(freqInput.value), 4.0);
          frequencyRef.contents = value;
          freqValue.textContent = value.toString();
        }));
  console.log("Wavy lines controls created");
}

function createSketch() {
  createControls();
  var sketchFn = PlotterFrame.createPlotterSketch(draw);
  var wrappedSketch = function () {
    return function (p) {
      sketchFn()(p);
      p.mousePressed = (function () {
          var currentMarginMm = PlotterFrame.currentMarginMm.contents;
          var currentPaddingMm = PlotterFrame.currentPaddingMm.contents;
          var totalSpacePx = (currentMarginMm + currentPaddingMm) * 3.7795275591;
          var mouseX = p.mouseX - totalSpacePx;
          var mouseY = p.mouseY - totalSpacePx;
          var currentPaper = PlotterFrame.getCurrentPaperSize();
          if (!(mouseX >= 0.0 && mouseX <= currentPaper.width && mouseY >= 0.0 && mouseY <= currentPaper.height)) {
            return ;
          }
          focalPointLockedRef.contents = !focalPointLockedRef.contents;
          if (!focalPointLockedRef.contents) {
            return ;
          }
          var centerYFixed = currentPaper.height / 2.0;
          focalPointRef.contents = [
            mouseX,
            centerYFixed
          ];
        });
    };
  };
  return wrappedSketch();
}

export {
  numLinesRef ,
  amplitudeRef ,
  gapSizeRef ,
  frequencyRef ,
  focalPointRef ,
  focalPointLockedRef ,
  draw ,
  createControls ,
  createSketch ,
}
/* PlotterFrame Not a pure module */
